### ISSUE TITLE
inconsistent licensing

### ISSUE THREAD

**Issue by ltalirz** [muhrin/pytray#2]
Hi @muhrin , I've just looked into the dependencies of AiiDA to make sure they are consistent with our license.

In the process, I noticed that kiwipy depends on pytray, which is GPL licensed.
According to the [README](https://github.com/aiidateam/kiwipy), kiwipy is both MIT and GPL licensed but in my understanding this is not compatible with using a GPL licensed dependency (`pytray`) that is imported in kiwipy and thus required for kiwipy to work.

Would you mind adding MIT as a dual option for pytray as well?

**Comment by muhrin** [comment]
Hi Leo, thanks for getting in touch.

It's true, I hadn't thought through the web of connections before.

Personally I have a strong preference for GPL (or share-alike in general) and would much prefer all of them were GPL.  Now, I recognise that this isn't realistic post-hoc.  In fact, that's the reason why `kiwiPy` (and some of the other libraries I've authored) have a dual MIT and GPL: Not because the GPL part changes anything just to remind people that they can use it if they want.

So, my thoughts with `pytray` are that I'd rather grant a perpetual license that allows `kiwiPy` to use `pytray`, say under MIT terms, rather than make a wholesale change to `pytray`.  My longer term goal is to transition as much as possible to share-alike and it would be painful for me to move away from that goal with pytray.

What do you think?

**Comment by ltalirz** [comment]
hey Martin, thanks for the quick reply!

> So, my thoughts with `pytray` are that I'd rather grant a perpetual license that allows `kiwiPy` to use `pytray`, say under MIT terms, rather than make a wholesale change to `pytray`.

In principle that could be enough; the question is just whether you will need a lawyer to write that sentence ;-)

For example, the sentence would need to somehow make clear that it also applies to any package that uses kiwipy as a dependency (think aiida-core which depends on pytray through kiwipy and therefore can be thought of as "linking" to pytray). Given that, could then another package simply circumvent the copyleft clause for pytray by also adding a dependency on kiwipy? Writing this down is probably not trivial... 

Since pytray was inserted "below" an existing tree of MIT-licensed software, I would personally suggest to take the bullet this time and add the MIT dual license. I don't really see another solution that does not potentially lead to headaches down the line.

**Comment by muhrin** [comment]
Let me have a think about it.

So `pytray` isn't just used by `kiwiPy`, it's basically a utilities library that is used by a bunch of my codes (some of them with no AiiDA overlap).

One thing that could be OK for me in this case is having a license that essentially allows linking to `pytray` without requiring copyleft, while requiring it of any derivative works (e.g. forks).  I think LGPL does this.  I'll double check and if you are OK with that solution I can relicense the code.

**Comment by ltalirz** [comment]
Indeed, in my understanding the LGPL would accomplish our goal best here (does not need to be MIT).

**Comment by muhrin** [comment]
Thanks Leo!  I've made the change in https://github.com/muhrin/pytray/commit/c41dbaecd1bb8468fa24b2a5e0d75d4e58122ec1.  I'll put out a release shortly.

**Comment by ltalirz** [comment]
Cheers!
